Multiple Policy Files
infratographer/permissions-api pull request #231
Opened 2024-04-04 18:28 UTC by jacobsee

Update policy app config & config loader to support multiple policy files.
Files are merged and the merged policy document is validated after all files are loaded.
Added a check to disallow multiple bindings of the same action to the same type.

2024-04-04 18:47 UTC, bailinhe submitted a review, later dismissed
LGTM 🚀

2024-04-04 18:52 UTC, mikemrm commented on internal/iapl/policy.go
> +		mergedPolicy.Unions = append(mergedPolicy.Unions, filePolicy.Unions...)
Something that worries me, is the policy document getting extended and this function getting forgotten about.

Possibly having a method on the policy document that accepts another document and merges them so the logic is kept within the struct methods and a little closer to home feels safer? But I'm not sure how realistic my concern is. But thought I'd mention it.

2024-04-04 18:56 UTC, mikemrm submitted a review, later dismissed
Looks good. I think there might be one potential change. But I'm not sure it a concern we might really have.

2024-04-04 19:03 UTC, jnschaeffer requested changes
I will be bad cop here: Let's document the merge logic in a Markdown file in the docs directory.

2024-04-04 21:11 UTC, jnschaeffer submitted a review, later dismissed

2024-04-05 01:08 UTC, mikemrm requested changes
I believe the only thing missing now is the values.yaml doesn't have a reference which is helpful for someone trying to figure out the configuration the the helm values.

2024-04-05 01:21 UTC, mikemrm submitted a review, later dismissed

2024-04-05 18:43 UTC, mikemrm commented on internal/iapl/policy.go
> +	}
Since we only accept yaml files, we might want to exclude non `.yml` or `.yaml` extensions.

2024-04-05 18:56 UTC, mikemrm approved these changes

2024-04-05 19:15 UTC, merged